// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztuzaovpqffbafjspvcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0dXphb3ZwcWZmYmFmanNwdmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDI3OTYsImV4cCI6MjA2NjkxODc5Nn0.L9HPExUaSI6JLE7hnNNOulWH43-3mUQAAJ1aWy1lwMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});